### ISSUE TITLE
Get multiple specific books at a time

### ISSUE THREAD

**Issue by WeebNetsu** [Zekfad/nhentai_dart#14]
Currently you have a request limit, so when calling `.getBook()` too many times in too short durations, you will receive `ApiClientException`. Is there a way to get a list of specific books, similar to `getBook`, but for multiple books specified by their id?

**Comment by Zekfad** [comment]
I believe there is no such API, the only way to get book is by direct request or indirectly from search result.
Search doesn't seem to have any id filters, so maximum I can suggest is to search for recent (`*`) in first pass, and get missing pieces in second pass.

**Comment by WeebNetsu** [comment]
Damn, that sucks! Thanks for tips :)
