### ISSUE TITLE
...

### ISSUE THREAD

**Issue by OtmaniCodes** [Zekfad/nhentai_dart#5]

**Comment by Zekfad** [comment]
API is up, locally I can run API.
Recently there was enabled Cloudflare protection on API endpoints. Do you use any method to pass `cf_clearance` cookie?

**Comment by AhmedCodor** [comment]
Thanks for replying,
This is how I'm using the package for now

` 
@override
  initState() {
    super.initState();
    getBook();
  }

  Future<void> getBook() async {
    final api = API();
    final Book? book = await api.getBook(177013);
    if (book == null) {
      throw Exception('Something went wrong.');
    } else {
      print('all is fine');
    }

// Short book summary
    // print(
    //   'Book: $book\n'
    //   'Artists: ${book.tags.artists.join(', ')}\n'
    //   'Languages: ${book.tags.languages.join(', ')}\n'
    //   'Cover: ${book.cover.getUrl(api: api)}\n'
    //   'First page: ${book.pages.first.getUrl(api: api)}\n'
    //   'First page thumbnail: ${book.pages.first.thumbnail.getUrl(api: api)}\n',
    // );
  }
`
and this is what gets logged:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Unexpected character (at character 1)
E/flutter ( 7760): <!DOCTYPE html>
E/flutter ( 7760): ^
E/flutter ( 7760): 
E/flutter ( 7760): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
E/flutter ( 7760): #1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1250:9)
E/flutter ( 7760): #2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:915:22)
E/flutter ( 7760): #3      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
E/flutter ( 7760): #4      JsonDecoder.convert (dart:convert/json.dart:612:36)
E/flutter ( 7760): #5      JsonCodec.decode (dart:convert/json.dart:216:41)
E/flutter ( 7760): #6      jsonDecode (dart:convert/json.dart:155:10)
E/flutter ( 7760): #7      API._getJson (package:nhentai/src/api.dart:104:18)
E/flutter ( 7760): <asynchronous suspension>
E/flutter ( 7760): #8      API.getBook (package:nhentai/src/api.dart:164:7)
E/flutter ( 7760): <asynchronous suspension>
E/flutter ( 7760): #9      _HentaiBooksState.getBook (package:miss_domina/src/view/screens/nhentai/nhentai.dart:22:24)
E/flutter ( 7760): <asynchronous suspension>
```

**Comment by Zekfad** [comment]
This is actually the same as #2. The reason for this is that website use Cloudflare, so instead of API response you've got Cloudflare HTML challenge (captcha in other words). we are currently looking for a good solution for this.

**Comment by AhmedCodor** [comment]
> This is actually the same as #2. The reason for this is that website use Cloudflare, so instead of API response you've got Cloudflare HTML challenge (captcha in other words). we are currently looking for a good solution for this.

Can you please give an approximation of how long would it take until this problem is solved?

**Comment by Zekfad** [comment]
No hard ETA for this one, when I'll have some free time I'll address this issue. Soft ETA is about a week.
Soon we'll change API to make it easier to pass Cookies to the client, this would unlock a workaround with a manual cookie retrieval (see https://github.com/Zekfad/nhentai-api/issues/25 for more info)
